### ISSUE TITLE
app.js2M加载慢有解决方法？

### ISSUE THREAD

**Issue by CCCpan** [zhaohaodang/vue-WeChat#12]
app.js2M加载慢有解决方法？我这每次打开或者 返回需要14s，有什么办法优化么？，项目做得真心赞

**Comment by CCCpan** [comment]
https://vue2-wechat.github.io/#/
这个里面的加载资源小很多，加载很快

**Comment by zhaohaodang** [comment]
尝试一下[路由懒加载](http://router.vuejs.org/zh-cn/advanced/lazy-loading.html)
