### ISSUE TITLE
路由设置方式疑惑

### ISSUE THREAD

**Issue by flyingrookie** [zhaohaodang/vue-WeChat#21]
楼主你好,不太懂你这种路由配置,一般都是在上面把所有组件import进来,然后设置路由,你这种require([''])方式有什么特别吗还有resolve用法

**Comment by zhaohaodang** [comment]
看这路由懒加载 https://router.vuejs.org/zh-cn/advanced/lazy-loading.html

**Comment by flyingrookie** [comment]
谢谢

**Comment by flyingrookie** [comment]
懒加载要不要在webpack文件设置懒加载路径等属性还是自动生成
