### ISSUE TITLE
好像缺个登陆页。哈哈

### ISSUE THREAD

**Issue by jacoblai** [zhaohaodang/vue-WeChat#24]
如题

**Comment by zhaohaodang** [comment]
登陆感觉不重要

**Comment by wwqgtxx** [comment]
仿就仿个全套的嘛

**Comment by zhaohaodang** [comment]
有道理

**Comment by wwqgtxx** [comment]
顺便提几个建议
1.统一一下整个项目的开发风格嘛，现在的项目同时用裸css，scss，less三种样式表，同时有得样式表内联在.vue文件中，有得在/assets目录下，显得非常混乱。
2.根据vue官方的规范，在.vue中的<style>内不应该使用@import而是应该使用src属性，对于<script>部分同样不推荐结尾加不必要的分号
3.建议分清npm的`dependencies`和`devDependencies`
