### ISSUE TITLE
build 报错文件路径不对

### ISSUE THREAD

**Issue by bloodspasm** [zhaohaodang/vue-WeChat#25]
build 无非正常显示
<img width="745" alt="2018-06-05 3 37 09" src="https://user-images.githubusercontent.com/10420472/40961865-6ab97c40-68d6-11e8-878f-41986cbd1d0b.png">

修改index.js -> assetsPublicPath: './',

但是还是有部分文件无法加载导致icon无法显示
<img width="704" alt="2018-06-05 3 37 25" src="https://user-images.githubusercontent.com/10420472/40961901-826f760a-68d6-11e8-99d7-f84bdb958878.png">

**Comment by zhaohaodang** [comment]
别修改assetsPublicPath，试试在dist目录下启动一个web服务
