### ISSUE TITLE
建议改成vue-cli3.0

### ISSUE THREAD

**Issue by Jacknode** [zhaohaodang/vue-WeChat#29]

**Comment by davy2018666** [comment]
请问大佬 这个后端用什么开发的呢 发不了信息

**Comment by linjinquan007** [comment]
前端nodejs 没后台


 
---原始邮件---
发件人: "davy2018666"<notifications@github.com>
发送时间: 2019年7月17日(星期三) 晚上6:01
收件人: "zhaohaodang/vue-WeChat"<vue-WeChat@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [zhaohaodang/vue-WeChat] 建议改成vue-cli3.0 (#29)



请问大佬 这个后端用什么开发的呢 发不了信息

**Comment by davy2018666** [comment]
大佬 能加个好友吗

linjinquan007 <notifications@github.com> 于2019年7月17日周三 下午6:07写道：

**Comment by zhaohaodang** [comment]
已经改成vue-cli 4啦
