### ISSUE TITLE
这项目没有维护了吗

### ISSUE THREAD

**Issue by yanceking** [zhaohaodang/vue-WeChat#31]

**Comment by linjinquan007** [comment]
工作太忙，没时间，qq269115077私聊

---原始邮件---
发件人: "yanceKing"<notifications@github.com&gt;
发送时间: 2020年7月22日(周三) 上午10:51
收件人: "zhaohaodang/vue-WeChat"<vue-WeChat@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [zhaohaodang/vue-WeChat] 这项目没有维护了吗 (#31)

**Comment by zhaohaodang** [comment]
最近用vue-cli4重构了一下
