### ISSUE TITLE
请问一下，这个我可以在uniapp 项目中作为一个组件使用吗？

### ISSUE THREAD

**Issue by 1761669469** [zhaohaodang/vue-WeChat#32]
请问一下，我做的是一个uniapp的项目，需要兼容小程序，ios, 以及安卓，现在需要一个即时通讯的功能，但是现在uniapp 没有一个好一点的即时通讯组件，我能否将您这个项目放在uniapp作为一个组件使用呢？可以的话能提供一下方法吗？

**Comment by zhaohaodang** [comment]
不能

**Comment by 1761669469** [comment]
好的，谢谢啊，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhaohaodang"<notifications@github.com&gt;; 
发送时间: 2020年8月28日(星期五) 下午4:28
收件人: "zhaohaodang/vue-WeChat"<vue-WeChat@noreply.github.com&gt;; 
抄送: "头条新闻"<1761669469@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhaohaodang/vue-WeChat] 请问一下，这个我可以在uniapp 项目中作为一个组件使用吗？ (#32)





 
不能
