### ISSUE TITLE
消息列表组件

### ISSUE THREAD

**Issue by tyzamy** [zhaohaodang/vue-WeChat#46]
你好，大神，我想问下mes-item页面中的props:['item']中的item里面的数据在哪里？

**Comment by zhaohaodang** [comment]
https://github.com/zhaohaodang/vue-WeChat/blob/master/src/components/wechat/wechat.vue#L6

**Comment by tyzamy** [comment]
谢谢啦！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaohaodang/vue-WeChat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 上午10:00
***@***.***&gt;;
抄送:&nbsp;"�7�7�9�8see ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhaohaodang/vue-WeChat] 消息列表组件 (#46)





 
https://github.com/zhaohaodang/vue-WeChat/blob/master/src/components/wechat/wechat.vue#L6
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
