### ISSUE TITLE
关于本地运行的问题

### ISSUE THREAD

**Issue by bailichen** [zhaohaodang/vue-WeChat#6]
代码clone后在本地运行的时候，点击底部的导航，点击第二遍的时候页面的数据会不存在了 ，也没有报错，不知道什么原因，运行命令： npm run dev

**Comment by bailichen** [comment]
可以说明一下伪元素实现字体图标是怎么实现的吗，谢谢

**Comment by zhaohaodang** [comment]
我需要知道你的运行环境重现bug

**Comment by bailichen** [comment]
运行环境是window7系统， node版本是6.9.1

**Comment by zhaohaodang** [comment]
网页的运行环境

**Comment by bailichen** [comment]
谷歌浏览器 版本 52.0.2743.116 (64-bit)

**Comment by zhaohaodang** [comment]
chrome未能重现这个bug，尝试升级chrome版本或者审查元素查看页面渲染情况
