### ISSUE TITLE
不支持华为P9浏览器？

### ISSUE THREAD

**Issue by cnszwjc** [zhaohaodang/vue-WeChat#9]
项目已克隆本地，并安装运行成功，可在电脑上浏览，但在华为P9手机的浏览器里打开应用时不显示网页内容，用微信内置浏览器可正常查看。请问什么原因？如何解决？
谢谢！

**Comment by zhaohaodang** [comment]
目前测试机仅有iPhone 6s/5s、vivoX9，并不保证兼容其他机型
